name: "CoreOSC build"
on: 
  pull_request:
    branches: [ "master" ]
  push:
    tags:
      - '*.*.*'
    branches:
      - 'feature/ci-build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build -c Release /p:Version=${{ github.ref_name }}

      - name: Test
        run: dotnet test -c Release

      - name: Pack
        run: dotnet pack -c Release -o .

      - name: Push artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coreosc-nupkg
          path: *.nupkg

  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: build
    if: github.ref_type == 'tag'
    steps:
      - name: Check matching tag
        run: |
          if [[ ! ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Tag does not match SemVer notation!"
              exit 1
          fi

      - name: Pull artifacts
        uses: actions/download-artifact@v4
        with:
          name: coreosc-nupkg

      - name: Publish to repo
        run: |
          dotnet nuget push *.nupkg -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -k ${{ secrets.GITHUB_TOKEN }}
